apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  strategy:
  {{- if eq .Values.stage "development"}}
    type: Recreate
  {{- else }}
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  {{- end }}
  replicas: {{ ternary 1 0 .Values.enabled }}
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: diploi-pull-secret
      initContainers: 
        - name: create-db
          image: postgres:13  # Ensure this matches your PostgreSQL version
          env:
            - name: PGPASSWORD
              value: {{ .Values.envMap.PASSWORD.value | quote }}
          # TODO: What if psql isn't ready?
          command:
            - sh
            - -c
            - |
              set -e
              DB_EXISTS=$(psql -h {{ .Values.envMap.HOST.value | quote }} -U {{ .Values.envMap.USER.value | quote }} -tc "SELECT 1 FROM pg_database WHERE datname = '{{ .Values.envMap.DATABASE.value }}'" | xargs)
              if [ "$DB_EXISTS" != "1" ]; then
                psql -h {{ .Values.envMap.HOST.value }} -U {{ .Values.envMap.USER.value }} -c "CREATE DATABASE {{ .Values.envMap.DATABASE.value }}"
              fi

              USER_EXISTS=$(psql -h {{ .Values.envMap.HOST.value }} -U {{ .Values.envMap.USER.value }} -tc "SELECT 1 FROM pg_roles WHERE rolname='{{ .Values.envMap.USER.value }}'" | xargs)
              if [ "$USER_EXISTS" != "1" ]; then
                psql -h {{ .Values.envMap.HOST.value }} -U {{ .Values.envMap.USER.value }} -c "CREATE USER {{ .Values.envMap.DB_USER.value }} WITH PASSWORD '{{ .Values.envMap.DB_PASSWORD.value }}' CREATEDB"
              fi

              psql -h {{ .Values.envMap.HOST.value }} -U {{ .Values.envMap.USER.value }} -c "GRANT ALL PRIVILEGES ON DATABASE {{ .Values.envMap.DATABASE.value }} TO {{ .Values.envMap.DB_USER.value }}"
  
      containers:
        - name: app
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          #workingDir: /app/{{ .Values.identifier }}
          #command: ['sh', '-c', 'echo The app is running! && sleep 10000']
          ports:
            - containerPort: 8069
          {{- if eq .Values.stage "development" }}
          workingDir: /app{{ .Values.folder }}
          {{- with .Values.containerCommands.developmentStart }}
          command:
            - /bin/sh
            - -c
            - |
          {{ . | nindent 14 }}
          {{- end }}
          {{- else }}
          {{- with .Values.containerCommands.productionStart }}
          command:
            - /bin/sh
            - -c
            - |
          {{ . | nindent 14 }}
          {{- end }}
          {{- end }}
          env:
            {{- range .Values.env }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.parameterGroups }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
            - name: APP_PUBLIC_URL
              value: {{ .Values.hosts.app }}
            - name: STAGE
              value: {{ .Values.stage }}
          volumeMounts:
            - name: data-mount
              mountPath: /var/lib/odoo
            {{- if hasKey .Values.storage "home" }}
            - name: home-mount
              mountPath: /home/odoo
            {{- end }}
            {{- if hasKey .Values.storage "extra-addons" }}
            - name: extra-addons-mount
              mountPath: /mnt/extra-addons
            {{- end }}
      volumes:
        - name: data-mount
          hostPath:
            path: {{ .Values.storage.data.hostPath }}
        {{- if hasKey .Values.storage "home" }}
        - name: home-mount
          hostPath:
            path: {{ .Values.storage.home.hostPath }}
        {{- end }}
        {{- if hasKey .Values.storage "extra-addons" }}
        - name: extra-addons-mount
          hostPath:
            path: {{ index (index .Values.storage "extra-addons") "hostPath" }}
        {{- end }}



